import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import './Planets.css';

const Planets = () => {
  const navigate = useNavigate();
  const { planetId } = useParams();
  const [loading, setLoading] = useState(true);
  const [selectedPlanet, setSelectedPlanet] = useState(null);
  const [chatMessages, setChatMessages] = useState([]);
  const [userInput, setUserInput] = useState('');
  const [sendingMessage, setSendingMessage] = useState(false);
  
  // Planet data
  const planets = [
    { 
      id: 'mercury', 
      name: 'Mercury', 
      color: '#a6a6a6',
      type: 'Terrestrial planet',
      distance: '57.9 million km',
      orbitalPeriod: '88 days',
      diameter: '4,879 km',
      moons: 0,
      gravity: '3.7 m/s²',
      temperature: '-173°C to 427°C',
      atmosphere: 'Minimal - Sodium, Potassium',
      description: 'Mercury is the smallest and innermost planet in the Solar System. It has a cratered surface similar to the Moon and virtually no atmosphere to retain heat, causing extreme temperature variations.',
      funFacts: [
        'Mercury has the most eccentric orbit of all planets in our solar system.',
        'A day on Mercury (sunrise to sunrise) lasts 176 Earth days.',
        'Despite being closest to the Sun, Venus is actually hotter than Mercury.',
        'Mercury has a large iron core that takes up about 60% of its mass.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/mercury-messenger-globe-pia15162-800x600-1.jpg'
    },
    { 
      id: 'venus', 
      name: 'Venus', 
      color: '#e39e54',
      type: 'Terrestrial planet',
      distance: '108.2 million km',
      orbitalPeriod: '225 days',
      diameter: '12,104 km',
      moons: 0,
      gravity: '8.87 m/s²',
      temperature: '462°C',
      atmosphere: 'Dense - Carbon dioxide, Nitrogen',
      description: 'Venus is the second planet from the Sun and the hottest planet in our solar system. It has a thick atmosphere that traps heat in a runaway greenhouse effect, making it even hotter than Mercury.',
      funFacts: [
        'Venus rotates backwards compared to other planets.',
        'A day on Venus is longer than its year.',
        'Venus has more volcanoes than any other planet in our solar system.',
        'The atmospheric pressure on Venus is 92 times greater than Earth\'s.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/venus-magellan-colorized-800x600-1.jpg'
    },
    { 
      id: 'earth', 
      name: 'Earth', 
      color: '#6b93d6',
      type: 'Terrestrial planet',
      distance: '149.6 million km',
      orbitalPeriod: '365.25 days',
      diameter: '12,742 km',
      moons: 1,
      gravity: '9.8 m/s²',
      temperature: '-88°C to 58°C',
      atmosphere: 'Nitrogen, Oxygen',
      description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth\'s surface is covered with water, making it unique among planets in our solar system.',
      funFacts: [
        'Earth is the only planet not named after a god or goddess.',
        'Earth\'s magnetic field is generated by its liquid iron outer core.',
        'Earth\'s atmosphere extends about 10,000 km into space.',
        'Earth is actually not a perfect sphere - it bulges at the equator.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/earth-dscovr-epic-july-6-2015-800x800-1.jpg'
    },
    { 
      id: 'mars', 
      name: 'Mars', 
      color: '#c1440e',
      type: 'Terrestrial planet',
      distance: '227.9 million km',
      orbitalPeriod: '687 days',
      diameter: '6,779 km',
      moons: 2,
      gravity: '3.72 m/s²',
      temperature: '-153°C to 20°C',
      atmosphere: 'Thin - Carbon dioxide',
      description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. Known as the "Red Planet" due to its reddish appearance from iron oxide on its surface, Mars has polar ice caps and evidence of ancient water flows.',
      funFacts: [
        'Mars has the largest dust storms in the solar system, sometimes engulfing the entire planet.',
        'Mars has the tallest mountain in the solar system - Olympus Mons.',
        'The red color comes from iron oxide (rust) on its surface.',
        'Mars has seasons similar to Earth because of its similar axial tilt.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/mars-perseverance-rover-meda-dust-devils-pia25269-800x600-1.jpg'
    },
    { 
      id: 'jupiter', 
      name: 'Jupiter', 
      color: '#e0ae6f',
      type: 'Gas giant',
      distance: '778.5 million km',
      orbitalPeriod: '11.86 years',
      diameter: '139,820 km',
      moons: 79,
      gravity: '24.79 m/s²',
      temperature: '-145°C',
      atmosphere: 'Hydrogen, Helium',
      description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets combined. Jupiter\'s iconic Great Red Spot is a giant storm that has been raging for hundreds of years.',
      funFacts: [
        'Jupiter has the shortest day of all planets, rotating once every 10 hours.',
        'The Great Red Spot is a storm that has been active for at least 400 years.',
        'Jupiter has the strongest magnetic field of any planet.',
        'If Jupiter had been about 80 times more massive, it would have become a star.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/jupiter-juno-perijove-53-pia25015-800x600-1.jpg'
    },
    { 
      id: 'saturn', 
      name: 'Saturn', 
      color: '#f4d4a9',
      type: 'Gas giant',
      distance: '1.4 billion km',
      orbitalPeriod: '29.46 years',
      diameter: '116,460 km',
      moons: 82,
      gravity: '10.44 m/s²',
      temperature: '-178°C',
      atmosphere: 'Hydrogen, Helium',
      description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is known for its spectacular ring system, which is made mostly of ice particles with a smaller amount of rocky debris and dust.',
      funFacts: [
        'Saturn\'s rings are made up of billions of particles of ice and rock.',
        'Saturn has a density lower than water - it would float if placed in a giant bathtub.',
        'Saturn has the fastest winds in the solar system, reaching up to 1,800 km/h.',
        'Saturn\'s moon Titan has lakes of liquid methane and ethane.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/saturn-cassini-grand-finale-pia21046-800x600-1.jpg'
    },
    { 
      id: 'uranus', 
      name: 'Uranus', 
      color: '#d1e7e7',
      type: 'Ice giant',
      distance: '2.9 billion km',
      orbitalPeriod: '84.01 years',
      diameter: '50,724 km',
      moons: 27,
      gravity: '8.87 m/s²',
      temperature: '-224°C',
      atmosphere: 'Hydrogen, Helium, Methane',
      description: 'Uranus is the seventh planet from the Sun and is unique among planets as it rotates on its side with an axial tilt of about 98 degrees. This gives it extreme seasons that last for decades and a magnetic field that is tilted and off-center.',
      funFacts: [
        'Uranus rotates on its side, likely due to a massive collision in its past.',
        'Uranus was the first planet discovered using a telescope.',
        'The blue-green color comes from methane in its atmosphere.',
        'Uranus has rings, but they\'re much fainter than Saturn\'s.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/uranus-voyager-2-800x600-1.jpg'
    },
    { 
      id: 'neptune', 
      name: 'Neptune', 
      color: '#5b5ddf',
      type: 'Ice giant',
      distance: '4.5 billion km',
      orbitalPeriod: '164.8 years',
      diameter: '49,244 km',
      moons: 14,
      gravity: '11.15 m/s²',
      temperature: '-214°C',
      atmosphere: 'Hydrogen, Helium, Methane',
      description: 'Neptune is the eighth and farthest known planet from the Sun. It is the fourth-largest planet by diameter and the third-largest by mass. Neptune has the strongest winds in the solar system, with speeds reaching up to 2,100 km/h.',
      funFacts: [
        'Neptune was predicted mathematically before it was observed.',
        'Neptune has only been visited by one spacecraft - Voyager 2 in 1989.',
        'Neptune\'s moon Triton orbits backwards and is likely a captured dwarf planet.',
        'Neptune has a Great Dark Spot similar to Jupiter\'s Great Red Spot.'
      ],
      image: 'https://science.nasa.gov/wp-content/uploads/2023/05/neptune-voyager-2-800x600-1.jpg'
    }
  ];
  
  // Load planet data based on URL parameter
  useEffect(() => {
    setLoading(true);
    
    if (planetId) {
      const planet = planets.find(p => p.id === planetId);
      if (planet) {
        setSelectedPlanet(planet);
        // Add welcome message for the selected planet
        setChatMessages([
          {
            role: 'assistant',
            content: `Welcome to the ${planet.name} information page! You can ask me any questions about ${planet.name} and I'll do my best to answer.`
          }
        ]);
      } else {
        navigate('/planets');
      }
    }
    
    setLoading(false);
  }, [planetId, navigate]);
  
  // Handle sending a message to the AI
  const handleSendMessage = async () => {
    if (!userInput.trim() || sendingMessage) return;
    
    const userMessage = userInput.trim();
    setUserInput('');
    setSendingMessage(true);
    
    // Add user message to chat
    setChatMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    
    try {
      // Read port from localStorage if available
      const serverPort = localStorage.getItem('serverPort') || '5004';
      
      // Send message to backend AI service
      const response = await axios.post(`http://localhost:${serverPort}/api/chat`, {
        messages: [
          { role: 'system', content: `You are an expert on the planet ${selectedPlanet.name}. Provide accurate, educational information about ${selectedPlanet.name} in response to user questions. Keep responses concise but informative.` },
          { role: 'user', content: userMessage }
        ]
      }, {
        timeout: 15000 // 15 second timeout
      });
      
      // Add AI response to chat
      if (response.data && response.data.response) {
        setChatMessages(prev => [...prev, { role: 'assistant', content: response.data.response }]);
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Error sending message:', error);
      
      // Add error message
      setChatMessages(prev => [
        ...prev, 
        { 
          role: 'assistant', 
          content: `I'm sorry, I'm having trouble connecting to my knowledge base about ${selectedPlanet.name}. Please try again later.` 
        }
      ]);
    } finally {
      setSendingMessage(false);
    }
  };
  
  // Handle key press for sending messages
  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };
  
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <div className="w-12 h-12 border-4 border-indigo-200 rounded-full animate-spin border-t-indigo-600"></div>
        <p className="text-gray-600 mt-4">Loading planet data...</p>
      </div>
    );
  }
  
  // If no planet is selected, show the planet selection screen
  if (!selectedPlanet) {
    return (
      <div className="planets-container">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <h1 className="text-3xl font-bold text-indigo-900 mb-6">
            Explore Our Solar System
          </h1>
          
          <p className="text-lg text-gray-600 mb-8">
            Click on a planet to learn more about it and chat with our AI assistant.
          </p>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {planets.map(planet => (
              <div 
                key={planet.id}
                className="planet-card"
                onClick={() => navigate(`/planets/${planet.id}`)}
              >
                <div 
                  className="planet-icon" 
                  style={{ backgroundColor: planet.color }}
                >
                  <span className="planet-name">{planet.name}</span>
                </div>
                <h3 className="planet-title">{planet.name}</h3>
                <p className="planet-type">{planet.type}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }
  
  // Show the selected planet details and chat
  return (
    <div className="planet-detail-container">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <a 
          href="/planets"
          className="flex items-center text-indigo-600 hover:text-indigo-800 mb-6"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
          </svg>
          Back to All Planets
        </a>
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Planet Info Column */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-lg shadow-md overflow-hidden">
              <div 
                className="h-64 bg-cover bg-center" 
                style={{ backgroundImage: `url(${selectedPlanet.image})` }}
              ></div>
              
              <div className="p-6">
                <h1 className="text-3xl font-bold text-indigo-900 mb-2">
                  {selectedPlanet.name}
                </h1>
                
                <p className="text-gray-600 mb-6">
                  {selectedPlanet.description}
                </p>
                
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className="planet-stat">
                    <span className="stat-label">Type</span>
                    <span className="stat-value">{selectedPlanet.type}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Distance from Sun</span>
                    <span className="stat-value">{selectedPlanet.distance}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Orbital Period</span>
                    <span className="stat-value">{selectedPlanet.orbitalPeriod}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Diameter</span>
                    <span className="stat-value">{selectedPlanet.diameter}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Moons</span>
                    <span className="stat-value">{selectedPlanet.moons}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Gravity</span>
                    <span className="stat-value">{selectedPlanet.gravity}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Temperature</span>
                    <span className="stat-value">{selectedPlanet.temperature}</span>
                  </div>
                  
                  <div className="planet-stat">
                    <span className="stat-label">Atmosphere</span>
                    <span className="stat-value">{selectedPlanet.atmosphere}</span>
                  </div>
                </div>
                
                <div className="bg-indigo-50 rounded-lg p-4">
                  <h3 className="text-lg font-semibold text-indigo-900 mb-2">Fun Facts</h3>
                  <ul className="space-y-2">
                    {selectedPlanet.funFacts.map((fact, index) => (
                      <li key={index} className="flex items-start">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-indigo-500 mr-2 mt-0.5" viewBox="0 0 20 20" fill="currentColor">
                          <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                        </svg>
                        <span className="text-gray-700">{fact}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
          
          {/* Chat Column */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-lg shadow-md h-full flex flex-col">
              <div className="p-4 bg-indigo-600 text-white rounded-t-lg">
                <h2 className="text-xl font-semibold">
                  Chat with {selectedPlanet.name} Expert
                </h2>
                <p className="text-indigo-100 text-sm">
                  Ask questions about {selectedPlanet.name}
                </p>
              </div>
              
              <div className="flex-1 overflow-y-auto p-4 space-y-4 chat-messages">
                {chatMessages.map((message, index) => (
                  <div 
                    key={index} 
                    className={`chat-message ${message.role === 'user' ? 'user-message' : 'assistant-message'}`}
                  >
                    <div className="message-content">
                      {message.content}
                    </div>
                  </div>
                ))}
                
                {sendingMessage && (
                  <div className="chat-message assistant-message">
                    <div className="message-content flex items-center">
                      <div className="typing-indicator">
                        <span></span>
                        <span></span>
                        <span></span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
              
              <div className="p-4 border-t">
                <div className="flex">
                  <textarea
                    className="flex-1 border rounded-l-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    placeholder={`Ask about ${selectedPlanet.name}...`}
                    rows="2"
                    value={userInput}
                    onChange={(e) => setUserInput(e.target.value)}
                    onKeyPress={handleKeyPress}
                  ></textarea>
                  <button
                    className="bg-indigo-600 text-white px-4 rounded-r-lg hover:bg-indigo-700 disabled:bg-indigo-300"
                    onClick={handleSendMessage}
                    disabled={!userInput.trim() || sendingMessage}
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 1.414L10.586 9H7a1 1 0 100 2h3.586l-1.293 1.293a1 1 0 101.414 1.414l3-3a1 1 0 000-1.414z" clipRule="evenodd" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Planets;
